### ISSUE TITLE
How to pass UID in join channel method?

### ISSUE THREAD

**Issue by tapannathvani** [AgoraIO-Community/iOS-UIKit#6]
Hi,

I want to pass UID at the time of recording then how can i pass in joinChannel method in your updated code..

**Comment by maxxfrazer** [comment]
version 1.0.3 should fix this, of course you can use the previous version in the meantime if there's any issues.

was the issue #2 ever resolved?

**Comment by tapannathvani** [comment]
#2 Yes that was fixed. Thanks

**Comment by tapannathvani** [comment]
Hi, what is the difference between this 2 pod files?
AgoraRtcEngine_iOS
or
AgoraUIKit_iOS

**Comment by maxxfrazer** [comment]
The first is the closed source SDK used to interact with Agora's RTC Engine, and the second (AgoraUIKit_iOS) is this open source package that acts as a wrapper to interact with the SDK with much less code. Mostly used to get started or for basic solutions.
Basically wrapping what you can find [here](https://docs.agora.io/en/Video/start_call_ios?platform=iOS) up into a small package.

If you need something more advanced, then I suggest creating your own UI, as that is not currently the intention for this repo.

I'll go ahead and close this issue because it seems it has been resolved with #7
