### ISSUE TITLE
[BUG] UI API called from background thread

### ISSUE THREAD

**Issue by subluush** [AgoraIO-Community/iOS-UIKit#70]
**Describe the bug**
Passing fetchToken=true in join channel call leads to 'UI API called from background thread' warning message from iOS and eventual crash.

Workaround is for app to manually get token and pass to Agora SDK instead of relying on Agora SDK to automatically fetch token.

**To Reproduce**
1. From main thread, call - AgoraViewer.viewer.join(channel: channeId, as: role, fetchToken: true, uid: uid)

**Expected behavior**
AgoraUIKit should process fetchToken result in main thread

**Screenshots**
<img width="678" alt="Screen Shot 2022-04-21 at 11 26 59 AM" src="https://user-images.githubusercontent.com/98977146/164530014-d85963d7-5744-4ee2-ab71-75d94f3e89a2.png">

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 15
 - Version 4.0.0-preview.12

**Comment by maxxfrazer** [comment]
thanks for the bug report! looks like the success handler for .join needs to come back to the main thread.
i'm currently working on the 1.8.1 release, so I'll add the patch in there and roll that out to the preview soon after

**Comment by maxxfrazer** [comment]
Just pushed an update `4.0.0-preview.13` that should fix your issue. Please note that since this version the library now has two separate parts, AgoraUIKit and AgoraRtmControl - double check that both of these libraries are included in your app target if using Swiftpm.

We'll be switching to 4.0.0-beta.1 soon, once some of the extensions are updated to work with it by the way
